name: CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    name: 'spfx-gulp-tools CI build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 2

      - name: Git config user
        run: |
          git config --local user.name "Rushbot"
          git config --local user.email "rushbot@users.noreply.github.com"

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 18.18.x

      - name: Verify Change Logs
        run: node common/scripts/install-run-rush.js change --verify

      - name: Rush Install
        run: node common/scripts/install-run-rush.js install

      - name: Rush Rebuild
        run: node common/scripts/install-run-rush.js rebuild --verbose --production
        env:
          BROWSERSLIST_IGNORE_OLD_DATA: 1
